services:
  bambooai-webapp:
    environment:
      - STAGE=prod
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bambooai-webapp
    ports:
      - "5001:5000"
    volumes:
      - ./bambooai:/app/bambooai
      - ./web_app:/app/web_app
      - ./.env:/app/web_app/.env
      - ./LLM_CONFIG.json:/app/web_app/LLM_CONFIG.json

    # Restart policy
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5000 --workers 1 --threads 4 --reload app:app
